groups:
  - name: ingestion-alerts
    interval: 30s
    rules:
      # 1. Échec détecté (critique) : >0 FAILED sur 5 minutes
      - alert: IngestionEchecDetecte
        expr: sum(rate(ingestion_runs_total{etat="FAILED"}[5m])) > 0
        for: 0m
        labels:
          severity: critical
          service: ingestion
          type: failure
        annotations:
          summary: "Échec détecté dans l'ingestion"
          description: "{{ printf \"%.0f\" $value }} échecs d'ingestion détectés dans les 5 dernières minutes"
          runbook_url: "https://wiki.company.com/runbook/ingestion-failure"

      # 2. Taux d'échec élevé : >2% pendant 15 minutes
      - alert: IngestionTauxEchecEleve
        expr: (100 * sum(rate(ingestion_runs_total{etat="FAILED"}[15m])) / sum(rate(ingestion_runs_total[15m]))) > 2
        for: 15m
        labels:
          severity: warning
          service: ingestion
          type: high_failure_rate
        annotations:
          summary: "Taux d'échec élevé dans l'ingestion"
          description: "Le taux d'échec d'ingestion est de {{ printf \"%.1f\" $value }}% sur 15 minutes (seuil: 2%)"
          runbook_url: "https://wiki.company.com/runbook/ingestion-high-failure-rate"

      # 3. Source muette : pas d'occurrence sur 75 minutes
      - alert: IngestionSourceMuette
        expr: (time() - max by (source) (ingestion_last_run_timestamp)) / 60 > 75
        for: 5m
        labels:
          severity: warning
          service: ingestion
          type: source_silent
        annotations:
          summary: "Source d'ingestion muette: {{ $labels.source }}"
          description: "La source {{ $labels.source }} n'a pas eu d'exécution depuis {{ printf \"%.0f\" $value }} minutes"
          runbook_url: "https://wiki.company.com/runbook/ingestion-source-silent"

      # 4. Latence p95 dégradée : p95 > 2× baseline (baseline = 30s)
      - alert: IngestionLatenceDegradee
        expr: histogram_quantile(0.95, sum(rate(ingestion_duration_seconds_bucket[5m])) by (le, source)) > 60
        for: 10m
        labels:
          severity: warning
          service: ingestion
          type: high_latency
        annotations:
          summary: "Latence p95 dégradée pour {{ $labels.source }}"
          description: "La latence p95 de {{ $labels.source }} est de {{ printf \"%.1f\" $value }}s (seuil: 60s)"
          runbook_url: "https://wiki.company.com/runbook/ingestion-high-latency"

      # 5. Surconsommation mémoire : mémoire >150 MB (p95)
      - alert: IngestionSurconsommationMemoire
        expr: histogram_quantile(0.95, sum(rate(ingestion_memory_usage_bytes_bucket[5m])) by (le, source)) / 1024 / 1024 > 150
        for: 10m
        labels:
          severity: warning
          service: ingestion
          type: high_memory_usage
        annotations:
          summary: "Surconsommation mémoire pour {{ $labels.source }}"
          description: "L'utilisation mémoire p95 de {{ $labels.source }} est de {{ printf \"%.0f\" $value }}MB (seuil: 150MB)"
          runbook_url: "https://wiki.company.com/runbook/ingestion-high-memory"

      # 5 bis. Surconsommation CPU : CPU >60s (p95)
      - alert: IngestionSurconsommationCPU
        expr: histogram_quantile(0.95, sum(rate(ingestion_cpu_usage_seconds_bucket[5m])) by (le, source)) > 60
        for: 10m
        labels:
          severity: warning
          service: ingestion
          type: high_cpu_usage
        annotations:
          summary: "Surconsommation CPU pour {{ $labels.source }}"
          description: "L'utilisation CPU p95 de {{ $labels.source }} est de {{ printf \"%.1f\" $value }}s (seuil: 60s)"
          runbook_url: "https://wiki.company.com/runbook/ingestion-high-cpu"

      # 6. Burst d'erreurs sur un Objet : >3 erreurs sur 10 minutes
      - alert: IngestionBurstErreurs
        expr: sum by (source, objet) (rate(ingestion_failures_total[10m])) * 600 > 3
        for: 2m
        labels:
          severity: warning
          service: ingestion
          type: error_burst
        annotations:
          summary: "Burst d'erreurs sur {{ $labels.source }}/{{ $labels.objet }}"
          description: "{{ printf \"%.0f\" $value }} erreurs détectées sur {{ $labels.source }}/{{ $labels.objet }} dans les 10 dernières minutes (seuil: 3)"
          runbook_url: "https://wiki.company.com/runbook/ingestion-error-burst"

      # Alertes supplémentaires pour la santé du système
      - alert: IngestionConsumerDown
        expr: up{job="ingestion-consumer"} == 0
        for: 2m
        labels:
          severity: critical
          service: ingestion
          type: service_down
        annotations:
          summary: "Consumer d'ingestion arrêté"
          description: "Le consumer d'ingestion n'est plus accessible"
          runbook_url: "https://wiki.company.com/runbook/ingestion-consumer-down"

      - alert: IngestionKafkaLag
        expr: kafka_consumer_lag_sum{topic="ingestion-logs"} > 1000
        for: 5m
        labels:
          severity: warning
          service: ingestion
          type: kafka_lag
        annotations:
          summary: "Lag Kafka élevé sur ingestion-logs"
          description: "Le lag Kafka sur le topic ingestion-logs est de {{ printf \"%.0f\" $value }} messages"
          runbook_url: "https://wiki.company.com/runbook/ingestion-kafka-lag"