server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Logs d'ingestion depuis les fichiers
  - job_name: ingestion-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: ingestion-logs
          __path__: /var/log/ingestion/*.log

    pipeline_stages:
      - json:
          expressions:
            etat: etat
            source: source
            objet: objet
            duree_secondes: duree_secondes
            memory_mb: memory_mb
            cpu_time_sec: cpu_time_sec
            description: description
            niveau: level

      - labels:
          etat:
          source:
          objet:
          niveau:

      - output:
          source: message

  # Logs des containers Docker
  - job_name: container-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["com.docker.compose.project=observability-stack"]

    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container_name'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'compose_service'

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time

      - labels:
          stream:

      - timestamp:
          source: time
          format: RFC3339Nano

      - output:
          source: output

  # Logs système (optionnel)
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system-logs
          __path__: /var/log/syslog

    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\w+\s+\d+\s+\d+:\d+:\d+)\s+(?P<hostname>\w+)\s+(?P<service>\w+):\s+(?P<message>.*)$'

      - labels:
          hostname:
          service:

      - timestamp:
          source: timestamp
          format: Jan 02 15:04:05